### ISSUE TITLE
Hey Malte fedt projekt

### ISSUE THREAD

**Issue by johanub** [MalteHB/-l-ctra#2]
Jeg har et spørgsmål angående hvordan du har fået fat på det danske Gigaword projekt, som du skriver at du har brugt til pretraning. Jeg sidder nemlig selv med et project hvor det ville være fedt at lege rundt med så stort et tekst corpus. 

Venlig hilsen Johan

**Comment by MalteHB** [comment]
Hej Johan,

Tusinde tak!

DAGW er endnu ikke offentliggjort, men bliver det snart. Paperen er til review og lige så snart den bliver udgivet så bliver dataen også tilgængelige.

God weekend!
